// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetMetatagsRequest struct {
	// The URL to retrieve metatags for.
	URL string `queryParam:"style=form,explode=true,name=url"`
}

func (o *GetMetatagsRequest) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

// GetMetatagsResponseBody - The retrieved metatags
type GetMetatagsResponseBody struct {
	// The meta description tag for the URL.
	Description *string `json:"description"`
	// The OpenGraph image for the URL.
	Image *string `json:"image"`
	// The meta title tag for the URL.
	Title *string `json:"title"`
}

func (o *GetMetatagsResponseBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetMetatagsResponseBody) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *GetMetatagsResponseBody) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

type GetMetatagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The retrieved metatags
	Object *GetMetatagsResponseBody
}

func (o *GetMetatagsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetMetatagsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetMetatagsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetMetatagsResponse) GetObject() *GetMetatagsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
