// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClicksDevices struct {
	// The number of clicks from this device
	Clicks float64 `json:"clicks"`
	// The name of the device
	Device string `json:"device"`
}

func (o *ClicksDevices) GetClicks() float64 {
	if o == nil {
		return 0.0
	}
	return o.Clicks
}

func (o *ClicksDevices) GetDevice() string {
	if o == nil {
		return ""
	}
	return o.Device
}
