// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClicksReferers struct {
	// The number of clicks from this referer
	Clicks float64 `json:"clicks"`
	// The name of the referer. If unknown, this will be `(direct)`
	Referer string `json:"referer"`
}

func (o *ClicksReferers) GetClicks() float64 {
	if o == nil {
		return 0.0
	}
	return o.Clicks
}

func (o *ClicksReferers) GetReferer() string {
	if o == nil {
		return ""
	}
	return o.Referer
}
