// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClicksTimeseries struct {
	// The number of clicks in the interval
	Clicks float64 `json:"clicks"`
	// The starting timestamp of the interval
	Start string `json:"start"`
}

func (o *ClicksTimeseries) GetClicks() float64 {
	if o == nil {
		return 0.0
	}
	return o.Clicks
}

func (o *ClicksTimeseries) GetStart() string {
	if o == nil {
		return ""
	}
	return o.Start
}
