// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ConflictCode - A short code indicating the error code returned.
type ConflictCode string

const (
	ConflictCodeConflict ConflictCode = "conflict"
)

func (e ConflictCode) ToPointer() *ConflictCode {
	return &e
}
func (e *ConflictCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "conflict":
		*e = ConflictCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConflictCode: %v", v)
	}
}

type ConflictError struct {
	// A short code indicating the error code returned.
	Code ConflictCode `json:"code"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
}

func (o *ConflictError) GetCode() ConflictCode {
	if o == nil {
		return ConflictCode("")
	}
	return o.Code
}

func (o *ConflictError) GetDocURL() *string {
	if o == nil {
		return nil
	}
	return o.DocURL
}

func (o *ConflictError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type Conflict struct {
	Error ConflictError `json:"error"`
}

func (o *Conflict) GetError() ConflictError {
	if o == nil {
		return ConflictError{}
	}
	return o.Error
}
