// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InternalServerErrorCode - A short code indicating the error code returned.
type InternalServerErrorCode string

const (
	InternalServerErrorCodeInternalServerError InternalServerErrorCode = "internal_server_error"
)

func (e InternalServerErrorCode) ToPointer() *InternalServerErrorCode {
	return &e
}
func (e *InternalServerErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "internal_server_error":
		*e = InternalServerErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InternalServerErrorCode: %v", v)
	}
}

type InternalServerErrorError struct {
	// A short code indicating the error code returned.
	Code InternalServerErrorCode `json:"code"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
}

func (o *InternalServerErrorError) GetCode() InternalServerErrorCode {
	if o == nil {
		return InternalServerErrorCode("")
	}
	return o.Code
}

func (o *InternalServerErrorError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *InternalServerErrorError) GetDocURL() *string {
	if o == nil {
		return nil
	}
	return o.DocURL
}

type InternalServerError struct {
	Error InternalServerErrorError `json:"error"`
}

func (o *InternalServerError) GetError() InternalServerErrorError {
	if o == nil {
		return InternalServerErrorError{}
	}
	return o.Error
}
