// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InviteExpiredCode - A short code indicating the error code returned.
type InviteExpiredCode string

const (
	InviteExpiredCodeInviteExpired InviteExpiredCode = "invite_expired"
)

func (e InviteExpiredCode) ToPointer() *InviteExpiredCode {
	return &e
}
func (e *InviteExpiredCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invite_expired":
		*e = InviteExpiredCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InviteExpiredCode: %v", v)
	}
}

type InviteExpiredError struct {
	// A short code indicating the error code returned.
	Code InviteExpiredCode `json:"code"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
}

func (o *InviteExpiredError) GetCode() InviteExpiredCode {
	if o == nil {
		return InviteExpiredCode("")
	}
	return o.Code
}

func (o *InviteExpiredError) GetDocURL() *string {
	if o == nil {
		return nil
	}
	return o.DocURL
}

func (o *InviteExpiredError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type InviteExpired struct {
	Error InviteExpiredError `json:"error"`
}

func (o *InviteExpired) GetError() InviteExpiredError {
	if o == nil {
		return InviteExpiredError{}
	}
	return o.Error
}
