// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SalesDevices struct {
	// The total amount of sales from this device
	Amount float64 `json:"amount"`
	// The name of the device
	Device string `json:"device"`
	// The number of sales from this device
	Sales float64 `json:"sales"`
}

func (o *SalesDevices) GetAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Amount
}

func (o *SalesDevices) GetDevice() string {
	if o == nil {
		return ""
	}
	return o.Device
}

func (o *SalesDevices) GetSales() float64 {
	if o == nil {
		return 0.0
	}
	return o.Sales
}
